#! /bin/sh

_() { bspc config "$@";  }
s() { pkill -x "$1"; { sleep 0.1; "$@"; } & }

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor DP-0.8 -d 1 2 3
bspc monitor HDMI-0 -d 4 5 6

_ window_gap 20
_ border_width 16
_ window_gap 12
_ top_padding 43

_ normal_border_color       '#282828'
_ active_border_color       '#282828'
_ focused_border_color      '#282828'

_ split_ratio          0.52
_ borderless_monocle   true
_ gapless_monocle      true

_ focus_follows_pointer    true

$HOME/.config/polybar/launch.sh
# s $HOME/.config/bspwm/borders
picom --config ~/.config/picom.conf -b
xset dpms 300
xset r rate 300 25
# $HOME/.fehbg
# dropbox start
# redshift
s unclutter

