#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor DP-0.8 -d 1 2 3
bspc monitor HDMI-0 -d 4 5 6

bspc config border_width 2
bspc config window_gap 12
bspc config top_padding 43

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

$HOME/.config/polybar/launch.sh
picom --config ~/.config/picom.conf -b
xset dpms 300
xset r rate 300 25
# $HOME/.fehbg
# dropbox start
# redshift
# unclutter

