#!/bin/bash

player_status=$(playerctl status 2> /dev/null)
if [[ $? -eq 0 ]]; then
    metadata="%{A1:playerctl play-pause:}%{A4:playerctl next:}%{A5:playerctl previous:}$(playerctl metadata artist) - $(playerctl metadata title)%{A}%{A}%{A}"
fi

# Foreground color formatting tags are optional
if [[ $player_status = "Playing" ]]; then
	echo "%{F#ebdbb2}$metadata%{F-}"
elif [[ $player_status = "Paused" ]]; then
    echo "%{F#999}$metadata%{F-}"
else
    echo ""
fi

